"""ajout de attribut video_path dans movie

Revision ID: 37f8a5275e86
Revises: 5a61f7bc3b58
Create Date: 2025-05-09 17:19:15.905457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f8a5275e86'
down_revision = '5a61f7bc3b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_file_path', sa.String(length=500), nullable=True))

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('video_file_path')

    # ### end Alembic commands ###
