"""ajout de attribut director_id dans movie

Revision ID: 5a61f7bc3b58
Revises: edb6ae059980
Create Date: 2025-05-09 03:22:31.714207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a61f7bc3b58'
down_revision = 'edb6ae059980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'directors', ['director_id'], ['id'])
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('director_id')

    # ### end Alembic commands ###
