from .user import User
from .movie import Movie
from .rating import Rating
from .recommendation import Recommendation
from .genre import Genre
from .director import Director
from .actor import Actor
from .review import Review
from .watchlist import Watchlist
from .favorite import Favorite
from .review import Review
from .role import Role
from .like import Like